( ak_0001 "# t a p y p a #" ("p-y" "y-p") )
( ak_0002 "# t a t y t a #" ("t-y" "y-t") )
( ak_0003 "# t a k y k a #" ("k-y" "y-k") )
( ak_0004 "# t a f y f a #" ("f-y" "y-f") )
( ak_0005 "# t a b y b a #" ("b-y" "y-b") )
( ak_0006 "# t a d y d a #" ("d-y" "y-d") )
( ak_0007 "# t a g y g a #" ("g-y" "y-g") )
( ak_0008 "# t a v y v a #" ("v-y" "y-v") )
( ak_0009 "# t a s y s a #" ("s-y" "y-s") )
( ak_0010 "# t a z y z a #" ("z-y" "y-z") )
( ak_0011 "# t a c y c a #" ("c-y" "y-c") )
( ak_0012 "# t a j y j a #" ("j-y" "y-j") )
( ak_0013 "# t a x y x a #" ("x-y" "y-x") )
( ak_0014 "# t a m y m a #" ("m-y" "y-m") )
( ak_0015 "# t a n y n a #" ("n-y" "y-n") )
( ak_0016 "# t a l y l a #" ("l-y" "y-l") )
( ak_0017 "# t a r y r a #" ("r-y" "y-r") )
( ak_0018 "# t a h y h a #" ("h-y" "y-h") )
( ak_0019 "# t a p e p a #" ("p-e" "e-p") )
( ak_0020 "# t a t e t a #" ("t-e" "e-t") )
( ak_0021 "# t a k e k a #" ("k-e" "e-k") )
( ak_0022 "# t a f e f a #" ("f-e" "e-f") )
( ak_0023 "# t a b e b a #" ("b-e" "e-b") )
( ak_0024 "# t a d e d a #" ("d-e" "e-d") )
( ak_0025 "# t a g e g a #" ("g-e" "e-g") )
( ak_0026 "# t a v e v a #" ("v-e" "e-v") )
( ak_0027 "# t a s e s a #" ("s-e" "e-s") )
( ak_0028 "# t a z e z a #" ("z-e" "e-z") )
( ak_0029 "# t a c e c a #" ("c-e" "e-c") )
( ak_0030 "# t a j e j a #" ("j-e" "e-j") )
( ak_0031 "# t a x e x a #" ("x-e" "e-x") )
( ak_0032 "# t a m e m a #" ("m-e" "e-m") )
( ak_0033 "# t a n e n a #" ("n-e" "e-n") )
( ak_0034 "# t a l e l a #" ("l-e" "e-l") )
( ak_0035 "# t a r e r a #" ("r-e" "e-r") )
( ak_0036 "# t a h e h a #" ("h-e" "e-h") )
( ak_0037 "# t a p a p a #" ("p-a" "a-p") )
( ak_0038 "# t a t a t a #" ("t-a" "a-t") )
( ak_0039 "# t a k a k a #" ("k-a" "a-k") )
( ak_0040 "# t a f a f a #" ("f-a" "a-f") )
( ak_0041 "# t a b a b a #" ("b-a" "a-b") )
( ak_0042 "# t a d a d a #" ("d-a" "a-d") )
( ak_0043 "# t a g a g a #" ("g-a" "a-g") )
( ak_0044 "# t a v a v a #" ("v-a" "a-v") )
( ak_0045 "# t a s a s a #" ("s-a" "a-s") )
( ak_0046 "# t a z a z a #" ("z-a" "a-z") )
( ak_0047 "# t a c a c a #" ("c-a" "a-c") )
( ak_0048 "# t a j a j a #" ("j-a" "a-j") )
( ak_0049 "# t a x a x a #" ("x-a" "a-x") )
( ak_0050 "# t a m a m a #" ("m-a" "a-m") )
( ak_0051 "# t a n a n a #" ("n-a" "a-n") )
( ak_0052 "# t a l a l a #" ("l-a" "a-l") )
( ak_0053 "# t a r a r a #" ("r-a" "a-r") )
( ak_0054 "# t a h a h a #" ("h-a" "a-h") )
( ak_0055 "# t a p o p a #" ("p-o" "o-p") )
( ak_0056 "# t a t o t a #" ("t-o" "o-t") )
( ak_0057 "# t a k o k a #" ("k-o" "o-k") )
( ak_0058 "# t a f o f a #" ("f-o" "o-f") )
( ak_0059 "# t a b o b a #" ("b-o" "o-b") )
( ak_0060 "# t a d o d a #" ("d-o" "o-d") )
( ak_0061 "# t a g o g a #" ("g-o" "o-g") )
( ak_0062 "# t a v o v a #" ("v-o" "o-v") )
( ak_0063 "# t a s o s a #" ("s-o" "o-s") )
( ak_0064 "# t a z o z a #" ("z-o" "o-z") )
( ak_0065 "# t a c o c a #" ("c-o" "o-c") )
( ak_0066 "# t a j o j a #" ("j-o" "o-j") )
( ak_0067 "# t a x o x a #" ("x-o" "o-x") )
( ak_0068 "# t a m o m a #" ("m-o" "o-m") )
( ak_0069 "# t a n o n a #" ("n-o" "o-n") )
( ak_0070 "# t a l o l a #" ("l-o" "o-l") )
( ak_0071 "# t a r o r a #" ("r-o" "o-r") )
( ak_0072 "# t a h o h a #" ("h-o" "o-h") )
( ak_0073 "# t a p i p a #" ("p-i" "i-p") )
( ak_0074 "# t a t i t a #" ("t-i" "i-t") )
( ak_0075 "# t a k i k a #" ("k-i" "i-k") )
( ak_0076 "# t a f i f a #" ("f-i" "i-f") )
( ak_0077 "# t a b i b a #" ("b-i" "i-b") )
( ak_0078 "# t a d i d a #" ("d-i" "i-d") )
( ak_0079 "# t a g i g a #" ("g-i" "i-g") )
( ak_0080 "# t a v i v a #" ("v-i" "i-v") )
( ak_0081 "# t a s i s a #" ("s-i" "i-s") )
( ak_0082 "# t a z i z a #" ("z-i" "i-z") )
( ak_0083 "# t a c i c a #" ("c-i" "i-c") )
( ak_0084 "# t a j i j a #" ("j-i" "i-j") )
( ak_0085 "# t a x i x a #" ("x-i" "i-x") )
( ak_0086 "# t a m i m a #" ("m-i" "i-m") )
( ak_0087 "# t a n i n a #" ("n-i" "i-n") )
( ak_0088 "# t a l i l a #" ("l-i" "i-l") )
( ak_0089 "# t a r i r a #" ("r-i" "i-r") )
( ak_0090 "# t a h i h a #" ("h-i" "i-h") )
( ak_0091 "# t a p u p a #" ("p-u" "u-p") )
( ak_0092 "# t a t u t a #" ("t-u" "u-t") )
( ak_0093 "# t a k u k a #" ("k-u" "u-k") )
( ak_0094 "# t a f u f a #" ("f-u" "u-f") )
( ak_0095 "# t a b u b a #" ("b-u" "u-b") )
( ak_0096 "# t a d u d a #" ("d-u" "u-d") )
( ak_0097 "# t a g u g a #" ("g-u" "u-g") )
( ak_0098 "# t a v u v a #" ("v-u" "u-v") )
( ak_0099 "# t a s u s a #" ("s-u" "u-s") )
( ak_0100 "# t a z u z a #" ("z-u" "u-z") )
( ak_0101 "# t a c u c a #" ("c-u" "u-c") )
( ak_0102 "# t a j u j a #" ("j-u" "u-j") )
( ak_0103 "# t a x u x a #" ("x-u" "u-x") )
( ak_0104 "# t a m u m a #" ("m-u" "u-m") )
( ak_0105 "# t a n u n a #" ("n-u" "u-n") )
( ak_0106 "# t a l u l a #" ("l-u" "u-l") )
( ak_0107 "# t a r u r a #" ("r-u" "u-r") )
( ak_0108 "# t a h u h a #" ("h-u" "u-h") )
( ak_0109 "# t a p ai p a #" ("p-ai" "ai-p") )
( ak_0110 "# t a t ai t a #" ("t-ai" "ai-t") )
( ak_0111 "# t a k ai k a #" ("k-ai" "ai-k") )
( ak_0112 "# t a f ai f a #" ("f-ai" "ai-f") )
( ak_0113 "# t a b ai b a #" ("b-ai" "ai-b") )
( ak_0114 "# t a d ai d a #" ("d-ai" "ai-d") )
( ak_0115 "# t a g ai g a #" ("g-ai" "ai-g") )
( ak_0116 "# t a v ai v a #" ("v-ai" "ai-v") )
( ak_0117 "# t a s ai s a #" ("s-ai" "ai-s") )
( ak_0118 "# t a z ai z a #" ("z-ai" "ai-z") )
( ak_0119 "# t a c ai c a #" ("c-ai" "ai-c") )
( ak_0120 "# t a j ai j a #" ("j-ai" "ai-j") )
( ak_0121 "# t a x ai x a #" ("x-ai" "ai-x") )
( ak_0122 "# t a m ai m a #" ("m-ai" "ai-m") )
( ak_0123 "# t a n ai n a #" ("n-ai" "ai-n") )
( ak_0124 "# t a l ai l a #" ("l-ai" "ai-l") )
( ak_0125 "# t a r ai r a #" ("r-ai" "ai-r") )
( ak_0126 "# t a h ai h a #" ("h-ai" "ai-h") )
( ak_0127 "# t a p ei p a #" ("p-ei" "ei-p") )
( ak_0128 "# t a t ei t a #" ("t-ei" "ei-t") )
( ak_0129 "# t a k ei k a #" ("k-ei" "ei-k") )
( ak_0130 "# t a f ei f a #" ("f-ei" "ei-f") )
( ak_0131 "# t a b ei b a #" ("b-ei" "ei-b") )
( ak_0132 "# t a d ei d a #" ("d-ei" "ei-d") )
( ak_0133 "# t a g ei g a #" ("g-ei" "ei-g") )
( ak_0134 "# t a v ei v a #" ("v-ei" "ei-v") )
( ak_0135 "# t a s ei s a #" ("s-ei" "ei-s") )
( ak_0136 "# t a z ei z a #" ("z-ei" "ei-z") )
( ak_0137 "# t a c ei c a #" ("c-ei" "ei-c") )
( ak_0138 "# t a j ei j a #" ("j-ei" "ei-j") )
( ak_0139 "# t a x ei x a #" ("x-ei" "ei-x") )
( ak_0140 "# t a m ei m a #" ("m-ei" "ei-m") )
( ak_0141 "# t a n ei n a #" ("n-ei" "ei-n") )
( ak_0142 "# t a l ei l a #" ("l-ei" "ei-l") )
( ak_0143 "# t a r ei r a #" ("r-ei" "ei-r") )
( ak_0144 "# t a h ei h a #" ("h-ei" "ei-h") )
( ak_0145 "# t a p oi p a #" ("p-oi" "oi-p") )
( ak_0146 "# t a t oi t a #" ("t-oi" "oi-t") )
( ak_0147 "# t a k oi k a #" ("k-oi" "oi-k") )
( ak_0148 "# t a f oi f a #" ("f-oi" "oi-f") )
( ak_0149 "# t a b oi b a #" ("b-oi" "oi-b") )
( ak_0150 "# t a d oi d a #" ("d-oi" "oi-d") )
( ak_0151 "# t a g oi g a #" ("g-oi" "oi-g") )
( ak_0152 "# t a v oi v a #" ("v-oi" "oi-v") )
( ak_0153 "# t a s oi s a #" ("s-oi" "oi-s") )
( ak_0154 "# t a z oi z a #" ("z-oi" "oi-z") )
( ak_0155 "# t a c oi c a #" ("c-oi" "oi-c") )
( ak_0156 "# t a j oi j a #" ("j-oi" "oi-j") )
( ak_0157 "# t a x oi x a #" ("x-oi" "oi-x") )
( ak_0158 "# t a m oi m a #" ("m-oi" "oi-m") )
( ak_0159 "# t a n oi n a #" ("n-oi" "oi-n") )
( ak_0160 "# t a l oi l a #" ("l-oi" "oi-l") )
( ak_0161 "# t a r oi r a #" ("r-oi" "oi-r") )
( ak_0162 "# t a h oi h a #" ("h-oi" "oi-h") )
( ak_0163 "# t a p au p a #" ("p-au" "au-p") )
( ak_0164 "# t a t au t a #" ("t-au" "au-t") )
( ak_0165 "# t a k au k a #" ("k-au" "au-k") )
( ak_0166 "# t a f au f a #" ("f-au" "au-f") )
( ak_0167 "# t a b au b a #" ("b-au" "au-b") )
( ak_0168 "# t a d au d a #" ("d-au" "au-d") )
( ak_0169 "# t a g au g a #" ("g-au" "au-g") )
( ak_0170 "# t a v au v a #" ("v-au" "au-v") )
( ak_0171 "# t a s au s a #" ("s-au" "au-s") )
( ak_0172 "# t a z au z a #" ("z-au" "au-z") )
( ak_0173 "# t a c au c a #" ("c-au" "au-c") )
( ak_0174 "# t a j au j a #" ("j-au" "au-j") )
( ak_0175 "# t a x au x a #" ("x-au" "au-x") )
( ak_0176 "# t a m au m a #" ("m-au" "au-m") )
( ak_0177 "# t a n au n a #" ("n-au" "au-n") )
( ak_0178 "# t a l au l a #" ("l-au" "au-l") )
( ak_0179 "# t a r au r a #" ("r-au" "au-r") )
( ak_0180 "# t a h au h a #" ("h-au" "au-h") )
( ak_0181 "# t a p ie p a #" ("p-ie" "ie-p") )
( ak_0182 "# t a t ie t a #" ("t-ie" "ie-t") )
( ak_0183 "# t a k ie k a #" ("k-ie" "ie-k") )
( ak_0184 "# t a f ie f a #" ("f-ie" "ie-f") )
( ak_0185 "# t a b ie b a #" ("b-ie" "ie-b") )
( ak_0186 "# t a d ie d a #" ("d-ie" "ie-d") )
( ak_0187 "# t a g ie g a #" ("g-ie" "ie-g") )
( ak_0188 "# t a v ie v a #" ("v-ie" "ie-v") )
( ak_0189 "# t a s ie s a #" ("s-ie" "ie-s") )
( ak_0190 "# t a z ie z a #" ("z-ie" "ie-z") )
( ak_0191 "# t a c ie c a #" ("c-ie" "ie-c") )
( ak_0192 "# t a j ie j a #" ("j-ie" "ie-j") )
( ak_0193 "# t a x ie x a #" ("x-ie" "ie-x") )
( ak_0194 "# t a m ie m a #" ("m-ie" "ie-m") )
( ak_0195 "# t a n ie n a #" ("n-ie" "ie-n") )
( ak_0196 "# t a l ie l a #" ("l-ie" "ie-l") )
( ak_0197 "# t a r ie r a #" ("r-ie" "ie-r") )
( ak_0198 "# t a h ie h a #" ("h-ie" "ie-h") )
( ak_0199 "# t a p ia p a #" ("p-ia" "ia-p") )
( ak_0200 "# t a t ia t a #" ("t-ia" "ia-t") )
( ak_0201 "# t a k ia k a #" ("k-ia" "ia-k") )
( ak_0202 "# t a f ia f a #" ("f-ia" "ia-f") )
( ak_0203 "# t a b ia b a #" ("b-ia" "ia-b") )
( ak_0204 "# t a d ia d a #" ("d-ia" "ia-d") )
( ak_0205 "# t a g ia g a #" ("g-ia" "ia-g") )
( ak_0206 "# t a v ia v a #" ("v-ia" "ia-v") )
( ak_0207 "# t a s ia s a #" ("s-ia" "ia-s") )
( ak_0208 "# t a z ia z a #" ("z-ia" "ia-z") )
( ak_0209 "# t a c ia c a #" ("c-ia" "ia-c") )
( ak_0210 "# t a j ia j a #" ("j-ia" "ia-j") )
( ak_0211 "# t a x ia x a #" ("x-ia" "ia-x") )
( ak_0212 "# t a m ia m a #" ("m-ia" "ia-m") )
( ak_0213 "# t a n ia n a #" ("n-ia" "ia-n") )
( ak_0214 "# t a l ia l a #" ("l-ia" "ia-l") )
( ak_0215 "# t a r ia r a #" ("r-ia" "ia-r") )
( ak_0216 "# t a h ia h a #" ("h-ia" "ia-h") )
( ak_0217 "# t a p io p a #" ("p-io" "io-p") )
( ak_0218 "# t a t io t a #" ("t-io" "io-t") )
( ak_0219 "# t a k io k a #" ("k-io" "io-k") )
( ak_0220 "# t a f io f a #" ("f-io" "io-f") )
( ak_0221 "# t a b io b a #" ("b-io" "io-b") )
( ak_0222 "# t a d io d a #" ("d-io" "io-d") )
( ak_0223 "# t a g io g a #" ("g-io" "io-g") )
( ak_0224 "# t a v io v a #" ("v-io" "io-v") )
( ak_0225 "# t a s io s a #" ("s-io" "io-s") )
( ak_0226 "# t a z io z a #" ("z-io" "io-z") )
( ak_0227 "# t a c io c a #" ("c-io" "io-c") )
( ak_0228 "# t a j io j a #" ("j-io" "io-j") )
( ak_0229 "# t a x io x a #" ("x-io" "io-x") )
( ak_0230 "# t a m io m a #" ("m-io" "io-m") )
( ak_0231 "# t a n io n a #" ("n-io" "io-n") )
( ak_0232 "# t a l io l a #" ("l-io" "io-l") )
( ak_0233 "# t a r io r a #" ("r-io" "io-r") )
( ak_0234 "# t a h io h a #" ("h-io" "io-h") )
( ak_0235 "# t a p ii p a #" ("p-ii" "ii-p") )
( ak_0236 "# t a t ii t a #" ("t-ii" "ii-t") )
( ak_0237 "# t a k ii k a #" ("k-ii" "ii-k") )
( ak_0238 "# t a f ii f a #" ("f-ii" "ii-f") )
( ak_0239 "# t a b ii b a #" ("b-ii" "ii-b") )
( ak_0240 "# t a d ii d a #" ("d-ii" "ii-d") )
( ak_0241 "# t a g ii g a #" ("g-ii" "ii-g") )
( ak_0242 "# t a v ii v a #" ("v-ii" "ii-v") )
( ak_0243 "# t a s ii s a #" ("s-ii" "ii-s") )
( ak_0244 "# t a z ii z a #" ("z-ii" "ii-z") )
( ak_0245 "# t a c ii c a #" ("c-ii" "ii-c") )
( ak_0246 "# t a j ii j a #" ("j-ii" "ii-j") )
( ak_0247 "# t a x ii x a #" ("x-ii" "ii-x") )
( ak_0248 "# t a m ii m a #" ("m-ii" "ii-m") )
( ak_0249 "# t a n ii n a #" ("n-ii" "ii-n") )
( ak_0250 "# t a l ii l a #" ("l-ii" "ii-l") )
( ak_0251 "# t a r ii r a #" ("r-ii" "ii-r") )
( ak_0252 "# t a h ii h a #" ("h-ii" "ii-h") )
( ak_0253 "# t a p iu p a #" ("p-iu" "iu-p") )
( ak_0254 "# t a t iu t a #" ("t-iu" "iu-t") )
( ak_0255 "# t a k iu k a #" ("k-iu" "iu-k") )
( ak_0256 "# t a f iu f a #" ("f-iu" "iu-f") )
( ak_0257 "# t a b iu b a #" ("b-iu" "iu-b") )
( ak_0258 "# t a d iu d a #" ("d-iu" "iu-d") )
( ak_0259 "# t a g iu g a #" ("g-iu" "iu-g") )
( ak_0260 "# t a v iu v a #" ("v-iu" "iu-v") )
( ak_0261 "# t a s iu s a #" ("s-iu" "iu-s") )
( ak_0262 "# t a z iu z a #" ("z-iu" "iu-z") )
( ak_0263 "# t a c iu c a #" ("c-iu" "iu-c") )
( ak_0264 "# t a j iu j a #" ("j-iu" "iu-j") )
( ak_0265 "# t a x iu x a #" ("x-iu" "iu-x") )
( ak_0266 "# t a m iu m a #" ("m-iu" "iu-m") )
( ak_0267 "# t a n iu n a #" ("n-iu" "iu-n") )
( ak_0268 "# t a l iu l a #" ("l-iu" "iu-l") )
( ak_0269 "# t a r iu r a #" ("r-iu" "iu-r") )
( ak_0270 "# t a h iu h a #" ("h-iu" "iu-h") )
( ak_0271 "# t a p ue p a #" ("p-ue" "ue-p") )
( ak_0272 "# t a t ue t a #" ("t-ue" "ue-t") )
( ak_0273 "# t a k ue k a #" ("k-ue" "ue-k") )
( ak_0274 "# t a f ue f a #" ("f-ue" "ue-f") )
( ak_0275 "# t a b ue b a #" ("b-ue" "ue-b") )
( ak_0276 "# t a d ue d a #" ("d-ue" "ue-d") )
( ak_0277 "# t a g ue g a #" ("g-ue" "ue-g") )
( ak_0278 "# t a v ue v a #" ("v-ue" "ue-v") )
( ak_0279 "# t a s ue s a #" ("s-ue" "ue-s") )
( ak_0280 "# t a z ue z a #" ("z-ue" "ue-z") )
( ak_0281 "# t a c ue c a #" ("c-ue" "ue-c") )
( ak_0282 "# t a j ue j a #" ("j-ue" "ue-j") )
( ak_0283 "# t a x ue x a #" ("x-ue" "ue-x") )
( ak_0284 "# t a m ue m a #" ("m-ue" "ue-m") )
( ak_0285 "# t a n ue n a #" ("n-ue" "ue-n") )
( ak_0286 "# t a l ue l a #" ("l-ue" "ue-l") )
( ak_0287 "# t a r ue r a #" ("r-ue" "ue-r") )
( ak_0288 "# t a h ue h a #" ("h-ue" "ue-h") )
( ak_0289 "# t a p ua p a #" ("p-ua" "ua-p") )
( ak_0290 "# t a t ua t a #" ("t-ua" "ua-t") )
( ak_0291 "# t a k ua k a #" ("k-ua" "ua-k") )
( ak_0292 "# t a f ua f a #" ("f-ua" "ua-f") )
( ak_0293 "# t a b ua b a #" ("b-ua" "ua-b") )
( ak_0294 "# t a d ua d a #" ("d-ua" "ua-d") )
( ak_0295 "# t a g ua g a #" ("g-ua" "ua-g") )
( ak_0296 "# t a v ua v a #" ("v-ua" "ua-v") )
( ak_0297 "# t a s ua s a #" ("s-ua" "ua-s") )
( ak_0298 "# t a z ua z a #" ("z-ua" "ua-z") )
( ak_0299 "# t a c ua c a #" ("c-ua" "ua-c") )
( ak_0300 "# t a j ua j a #" ("j-ua" "ua-j") )
( ak_0301 "# t a x ua x a #" ("x-ua" "ua-x") )
( ak_0302 "# t a m ua m a #" ("m-ua" "ua-m") )
( ak_0303 "# t a n ua n a #" ("n-ua" "ua-n") )
( ak_0304 "# t a l ua l a #" ("l-ua" "ua-l") )
( ak_0305 "# t a r ua r a #" ("r-ua" "ua-r") )
( ak_0306 "# t a h ua h a #" ("h-ua" "ua-h") )
( ak_0307 "# t a p uo p a #" ("p-uo" "uo-p") )
( ak_0308 "# t a t uo t a #" ("t-uo" "uo-t") )
( ak_0309 "# t a k uo k a #" ("k-uo" "uo-k") )
( ak_0310 "# t a f uo f a #" ("f-uo" "uo-f") )
( ak_0311 "# t a b uo b a #" ("b-uo" "uo-b") )
( ak_0312 "# t a d uo d a #" ("d-uo" "uo-d") )
( ak_0313 "# t a g uo g a #" ("g-uo" "uo-g") )
( ak_0314 "# t a v uo v a #" ("v-uo" "uo-v") )
( ak_0315 "# t a s uo s a #" ("s-uo" "uo-s") )
( ak_0316 "# t a z uo z a #" ("z-uo" "uo-z") )
( ak_0317 "# t a c uo c a #" ("c-uo" "uo-c") )
( ak_0318 "# t a j uo j a #" ("j-uo" "uo-j") )
( ak_0319 "# t a x uo x a #" ("x-uo" "uo-x") )
( ak_0320 "# t a m uo m a #" ("m-uo" "uo-m") )
( ak_0321 "# t a n uo n a #" ("n-uo" "uo-n") )
( ak_0322 "# t a l uo l a #" ("l-uo" "uo-l") )
( ak_0323 "# t a r uo r a #" ("r-uo" "uo-r") )
( ak_0324 "# t a h uo h a #" ("h-uo" "uo-h") )
( ak_0325 "# t a p ui p a #" ("p-ui" "ui-p") )
( ak_0326 "# t a t ui t a #" ("t-ui" "ui-t") )
( ak_0327 "# t a k ui k a #" ("k-ui" "ui-k") )
( ak_0328 "# t a f ui f a #" ("f-ui" "ui-f") )
( ak_0329 "# t a b ui b a #" ("b-ui" "ui-b") )
( ak_0330 "# t a d ui d a #" ("d-ui" "ui-d") )
( ak_0331 "# t a g ui g a #" ("g-ui" "ui-g") )
( ak_0332 "# t a v ui v a #" ("v-ui" "ui-v") )
( ak_0333 "# t a s ui s a #" ("s-ui" "ui-s") )
( ak_0334 "# t a z ui z a #" ("z-ui" "ui-z") )
( ak_0335 "# t a c ui c a #" ("c-ui" "ui-c") )
( ak_0336 "# t a j ui j a #" ("j-ui" "ui-j") )
( ak_0337 "# t a x ui x a #" ("x-ui" "ui-x") )
( ak_0338 "# t a m ui m a #" ("m-ui" "ui-m") )
( ak_0339 "# t a n ui n a #" ("n-ui" "ui-n") )
( ak_0340 "# t a l ui l a #" ("l-ui" "ui-l") )
( ak_0341 "# t a r ui r a #" ("r-ui" "ui-r") )
( ak_0342 "# t a h ui h a #" ("h-ui" "ui-h") )
( ak_0343 "# t a p uu p a #" ("p-uu" "uu-p") )
( ak_0344 "# t a t uu t a #" ("t-uu" "uu-t") )
( ak_0345 "# t a k uu k a #" ("k-uu" "uu-k") )
( ak_0346 "# t a f uu f a #" ("f-uu" "uu-f") )
( ak_0347 "# t a b uu b a #" ("b-uu" "uu-b") )
( ak_0348 "# t a d uu d a #" ("d-uu" "uu-d") )
( ak_0349 "# t a g uu g a #" ("g-uu" "uu-g") )
( ak_0350 "# t a v uu v a #" ("v-uu" "uu-v") )
( ak_0351 "# t a s uu s a #" ("s-uu" "uu-s") )
( ak_0352 "# t a z uu z a #" ("z-uu" "uu-z") )
( ak_0353 "# t a c uu c a #" ("c-uu" "uu-c") )
( ak_0354 "# t a j uu j a #" ("j-uu" "uu-j") )
( ak_0355 "# t a x uu x a #" ("x-uu" "uu-x") )
( ak_0356 "# t a m uu m a #" ("m-uu" "uu-m") )
( ak_0357 "# t a n uu n a #" ("n-uu" "uu-n") )
( ak_0358 "# t a l uu l a #" ("l-uu" "uu-l") )
( ak_0359 "# t a r uu r a #" ("r-uu" "uu-r") )
( ak_0360 "# t a h uu h a #" ("h-uu" "uu-h") )
( ak_0361 "# t a p iy p a #" ("p-iy" "iy-p") )
( ak_0362 "# t a t iy t a #" ("t-iy" "iy-t") )
( ak_0363 "# t a k iy k a #" ("k-iy" "iy-k") )
( ak_0364 "# t a f iy f a #" ("f-iy" "iy-f") )
( ak_0365 "# t a b iy b a #" ("b-iy" "iy-b") )
( ak_0366 "# t a d iy d a #" ("d-iy" "iy-d") )
( ak_0367 "# t a g iy g a #" ("g-iy" "iy-g") )
( ak_0368 "# t a v iy v a #" ("v-iy" "iy-v") )
( ak_0369 "# t a s iy s a #" ("s-iy" "iy-s") )
( ak_0370 "# t a z iy z a #" ("z-iy" "iy-z") )
( ak_0371 "# t a c iy c a #" ("c-iy" "iy-c") )
( ak_0372 "# t a j iy j a #" ("j-iy" "iy-j") )
( ak_0373 "# t a x iy x a #" ("x-iy" "iy-x") )
( ak_0374 "# t a m iy m a #" ("m-iy" "iy-m") )
( ak_0375 "# t a n iy n a #" ("n-iy" "iy-n") )
( ak_0376 "# t a l iy l a #" ("l-iy" "iy-l") )
( ak_0377 "# t a r iy r a #" ("r-iy" "iy-r") )
( ak_0378 "# t a h iy h a #" ("h-iy" "iy-h") )
( ak_0379 "# t a p uy p a #" ("p-uy" "uy-p") )
( ak_0380 "# t a t uy t a #" ("t-uy" "uy-t") )
( ak_0381 "# t a k uy k a #" ("k-uy" "uy-k") )
( ak_0382 "# t a f uy f a #" ("f-uy" "uy-f") )
( ak_0383 "# t a b uy b a #" ("b-uy" "uy-b") )
( ak_0384 "# t a d uy d a #" ("d-uy" "uy-d") )
( ak_0385 "# t a g uy g a #" ("g-uy" "uy-g") )
( ak_0386 "# t a v uy v a #" ("v-uy" "uy-v") )
( ak_0387 "# t a s uy s a #" ("s-uy" "uy-s") )
( ak_0388 "# t a z uy z a #" ("z-uy" "uy-z") )
( ak_0389 "# t a c uy c a #" ("c-uy" "uy-c") )
( ak_0390 "# t a j uy j a #" ("j-uy" "uy-j") )
( ak_0391 "# t a x uy x a #" ("x-uy" "uy-x") )
( ak_0392 "# t a m uy m a #" ("m-uy" "uy-m") )
( ak_0393 "# t a n uy n a #" ("n-uy" "uy-n") )
( ak_0394 "# t a l uy l a #" ("l-uy" "uy-l") )
( ak_0395 "# t a r uy r a #" ("r-uy" "uy-r") )
( ak_0396 "# t a h uy h a #" ("h-uy" "uy-h") )
( ak_0397 "# t a t y y t a #" ("y-y") )
( ak_0398 "# t a t y e t a #" ("y-e") )
( ak_0399 "# t a t y a t a #" ("y-a") )
( ak_0400 "# t a t y o t a #" ("y-o") )
( ak_0401 "# t a t y i t a #" ("y-i") )
( ak_0402 "# t a t y u t a #" ("y-u") )
( ak_0403 "# t a t y ai t a #" ("y-ai") )
( ak_0404 "# t a t y ei t a #" ("y-ei") )
( ak_0405 "# t a t y oi t a #" ("y-oi") )
( ak_0406 "# t a t y au t a #" ("y-au") )
( ak_0407 "# t a t y ie t a #" ("y-ie") )
( ak_0408 "# t a t y ia t a #" ("y-ia") )
( ak_0409 "# t a t y io t a #" ("y-io") )
( ak_0410 "# t a t y ii t a #" ("y-ii") )
( ak_0411 "# t a t y iu t a #" ("y-iu") )
( ak_0412 "# t a t y ue t a #" ("y-ue") )
( ak_0413 "# t a t y ua t a #" ("y-ua") )
( ak_0414 "# t a t y uo t a #" ("y-uo") )
( ak_0415 "# t a t y ui t a #" ("y-ui") )
( ak_0416 "# t a t y uu t a #" ("y-uu") )
( ak_0417 "# t a t y iy t a #" ("y-iy") )
( ak_0418 "# t a t y uy t a #" ("y-uy") )
( ak_0419 "# t a t e y t a #" ("e-y") )
( ak_0420 "# t a t e e t a #" ("e-e") )
( ak_0421 "# t a t e a t a #" ("e-a") )
( ak_0422 "# t a t e o t a #" ("e-o") )
( ak_0423 "# t a t e i t a #" ("e-i") )
( ak_0424 "# t a t e u t a #" ("e-u") )
( ak_0425 "# t a t e ai t a #" ("e-ai") )
( ak_0426 "# t a t e ei t a #" ("e-ei") )
( ak_0427 "# t a t e oi t a #" ("e-oi") )
( ak_0428 "# t a t e au t a #" ("e-au") )
( ak_0429 "# t a t e ie t a #" ("e-ie") )
( ak_0430 "# t a t e ia t a #" ("e-ia") )
( ak_0431 "# t a t e io t a #" ("e-io") )
( ak_0432 "# t a t e ii t a #" ("e-ii") )
( ak_0433 "# t a t e iu t a #" ("e-iu") )
( ak_0434 "# t a t e ue t a #" ("e-ue") )
( ak_0435 "# t a t e ua t a #" ("e-ua") )
( ak_0436 "# t a t e uo t a #" ("e-uo") )
( ak_0437 "# t a t e ui t a #" ("e-ui") )
( ak_0438 "# t a t e uu t a #" ("e-uu") )
( ak_0439 "# t a t e iy t a #" ("e-iy") )
( ak_0440 "# t a t e uy t a #" ("e-uy") )
( ak_0441 "# t a t a y t a #" ("a-y") )
( ak_0442 "# t a t a e t a #" ("a-e") )
( ak_0443 "# t a t a a t a #" ("a-a") )
( ak_0444 "# t a t a o t a #" ("a-o") )
( ak_0445 "# t a t a i t a #" ("a-i") )
( ak_0446 "# t a t a u t a #" ("a-u") )
( ak_0447 "# t a t a ai t a #" ("a-ai") )
( ak_0448 "# t a t a ei t a #" ("a-ei") )
( ak_0449 "# t a t a oi t a #" ("a-oi") )
( ak_0450 "# t a t a au t a #" ("a-au") )
( ak_0451 "# t a t a ie t a #" ("a-ie") )
( ak_0452 "# t a t a ia t a #" ("a-ia") )
( ak_0453 "# t a t a io t a #" ("a-io") )
( ak_0454 "# t a t a ii t a #" ("a-ii") )
( ak_0455 "# t a t a iu t a #" ("a-iu") )
( ak_0456 "# t a t a ue t a #" ("a-ue") )
( ak_0457 "# t a t a ua t a #" ("a-ua") )
( ak_0458 "# t a t a uo t a #" ("a-uo") )
( ak_0459 "# t a t a ui t a #" ("a-ui") )
( ak_0460 "# t a t a uu t a #" ("a-uu") )
( ak_0461 "# t a t a iy t a #" ("a-iy") )
( ak_0462 "# t a t a uy t a #" ("a-uy") )
( ak_0463 "# t a t o y t a #" ("o-y") )
( ak_0464 "# t a t o e t a #" ("o-e") )
( ak_0465 "# t a t o a t a #" ("o-a") )
( ak_0466 "# t a t o o t a #" ("o-o") )
( ak_0467 "# t a t o i t a #" ("o-i") )
( ak_0468 "# t a t o u t a #" ("o-u") )
( ak_0469 "# t a t o ai t a #" ("o-ai") )
( ak_0470 "# t a t o ei t a #" ("o-ei") )
( ak_0471 "# t a t o oi t a #" ("o-oi") )
( ak_0472 "# t a t o au t a #" ("o-au") )
( ak_0473 "# t a t o ie t a #" ("o-ie") )
( ak_0474 "# t a t o ia t a #" ("o-ia") )
( ak_0475 "# t a t o io t a #" ("o-io") )
( ak_0476 "# t a t o ii t a #" ("o-ii") )
( ak_0477 "# t a t o iu t a #" ("o-iu") )
( ak_0478 "# t a t o ue t a #" ("o-ue") )
( ak_0479 "# t a t o ua t a #" ("o-ua") )
( ak_0480 "# t a t o uo t a #" ("o-uo") )
( ak_0481 "# t a t o ui t a #" ("o-ui") )
( ak_0482 "# t a t o uu t a #" ("o-uu") )
( ak_0483 "# t a t o iy t a #" ("o-iy") )
( ak_0484 "# t a t o uy t a #" ("o-uy") )
( ak_0485 "# t a t i y t a #" ("i-y") )
( ak_0486 "# t a t i e t a #" ("i-e") )
( ak_0487 "# t a t i a t a #" ("i-a") )
( ak_0488 "# t a t i o t a #" ("i-o") )
( ak_0489 "# t a t i i t a #" ("i-i") )
( ak_0490 "# t a t i u t a #" ("i-u") )
( ak_0491 "# t a t i ai t a #" ("i-ai") )
( ak_0492 "# t a t i ei t a #" ("i-ei") )
( ak_0493 "# t a t i oi t a #" ("i-oi") )
( ak_0494 "# t a t i au t a #" ("i-au") )
( ak_0495 "# t a t i ie t a #" ("i-ie") )
( ak_0496 "# t a t i ia t a #" ("i-ia") )
( ak_0497 "# t a t i io t a #" ("i-io") )
( ak_0498 "# t a t i ii t a #" ("i-ii") )
( ak_0499 "# t a t i iu t a #" ("i-iu") )
( ak_0500 "# t a t i ue t a #" ("i-ue") )
( ak_0501 "# t a t i ua t a #" ("i-ua") )
( ak_0502 "# t a t i uo t a #" ("i-uo") )
( ak_0503 "# t a t i ui t a #" ("i-ui") )
( ak_0504 "# t a t i uu t a #" ("i-uu") )
( ak_0505 "# t a t i iy t a #" ("i-iy") )
( ak_0506 "# t a t i uy t a #" ("i-uy") )
( ak_0507 "# t a t u y t a #" ("u-y") )
( ak_0508 "# t a t u e t a #" ("u-e") )
( ak_0509 "# t a t u a t a #" ("u-a") )
( ak_0510 "# t a t u o t a #" ("u-o") )
( ak_0511 "# t a t u i t a #" ("u-i") )
( ak_0512 "# t a t u u t a #" ("u-u") )
( ak_0513 "# t a t u ai t a #" ("u-ai") )
( ak_0514 "# t a t u ei t a #" ("u-ei") )
( ak_0515 "# t a t u oi t a #" ("u-oi") )
( ak_0516 "# t a t u au t a #" ("u-au") )
( ak_0517 "# t a t u ie t a #" ("u-ie") )
( ak_0518 "# t a t u ia t a #" ("u-ia") )
( ak_0519 "# t a t u io t a #" ("u-io") )
( ak_0520 "# t a t u ii t a #" ("u-ii") )
( ak_0521 "# t a t u iu t a #" ("u-iu") )
( ak_0522 "# t a t u ue t a #" ("u-ue") )
( ak_0523 "# t a t u ua t a #" ("u-ua") )
( ak_0524 "# t a t u uo t a #" ("u-uo") )
( ak_0525 "# t a t u ui t a #" ("u-ui") )
( ak_0526 "# t a t u uu t a #" ("u-uu") )
( ak_0527 "# t a t u iy t a #" ("u-iy") )
( ak_0528 "# t a t u uy t a #" ("u-uy") )
( ak_0529 "# t a t ai y t a #" ("ai-y") )
( ak_0530 "# t a t ai e t a #" ("ai-e") )
( ak_0531 "# t a t ai a t a #" ("ai-a") )
( ak_0532 "# t a t ai o t a #" ("ai-o") )
( ak_0533 "# t a t ai i t a #" ("ai-i") )
( ak_0534 "# t a t ai u t a #" ("ai-u") )
( ak_0535 "# t a t ai ai t a #" ("ai-ai") )
( ak_0536 "# t a t ai ei t a #" ("ai-ei") )
( ak_0537 "# t a t ai oi t a #" ("ai-oi") )
( ak_0538 "# t a t ai au t a #" ("ai-au") )
( ak_0539 "# t a t ai ie t a #" ("ai-ie") )
( ak_0540 "# t a t ai ia t a #" ("ai-ia") )
( ak_0541 "# t a t ai io t a #" ("ai-io") )
( ak_0542 "# t a t ai ii t a #" ("ai-ii") )
( ak_0543 "# t a t ai iu t a #" ("ai-iu") )
( ak_0544 "# t a t ai ue t a #" ("ai-ue") )
( ak_0545 "# t a t ai ua t a #" ("ai-ua") )
( ak_0546 "# t a t ai uo t a #" ("ai-uo") )
( ak_0547 "# t a t ai ui t a #" ("ai-ui") )
( ak_0548 "# t a t ai uu t a #" ("ai-uu") )
( ak_0549 "# t a t ai iy t a #" ("ai-iy") )
( ak_0550 "# t a t ai uy t a #" ("ai-uy") )
( ak_0551 "# t a t ei y t a #" ("ei-y") )
( ak_0552 "# t a t ei e t a #" ("ei-e") )
( ak_0553 "# t a t ei a t a #" ("ei-a") )
( ak_0554 "# t a t ei o t a #" ("ei-o") )
( ak_0555 "# t a t ei i t a #" ("ei-i") )
( ak_0556 "# t a t ei u t a #" ("ei-u") )
( ak_0557 "# t a t ei ai t a #" ("ei-ai") )
( ak_0558 "# t a t ei ei t a #" ("ei-ei") )
( ak_0559 "# t a t ei oi t a #" ("ei-oi") )
( ak_0560 "# t a t ei au t a #" ("ei-au") )
( ak_0561 "# t a t ei ie t a #" ("ei-ie") )
( ak_0562 "# t a t ei ia t a #" ("ei-ia") )
( ak_0563 "# t a t ei io t a #" ("ei-io") )
( ak_0564 "# t a t ei ii t a #" ("ei-ii") )
( ak_0565 "# t a t ei iu t a #" ("ei-iu") )
( ak_0566 "# t a t ei ue t a #" ("ei-ue") )
( ak_0567 "# t a t ei ua t a #" ("ei-ua") )
( ak_0568 "# t a t ei uo t a #" ("ei-uo") )
( ak_0569 "# t a t ei ui t a #" ("ei-ui") )
( ak_0570 "# t a t ei uu t a #" ("ei-uu") )
( ak_0571 "# t a t ei iy t a #" ("ei-iy") )
( ak_0572 "# t a t ei uy t a #" ("ei-uy") )
( ak_0573 "# t a t oi y t a #" ("oi-y") )
( ak_0574 "# t a t oi e t a #" ("oi-e") )
( ak_0575 "# t a t oi a t a #" ("oi-a") )
( ak_0576 "# t a t oi o t a #" ("oi-o") )
( ak_0577 "# t a t oi i t a #" ("oi-i") )
( ak_0578 "# t a t oi u t a #" ("oi-u") )
( ak_0579 "# t a t oi ai t a #" ("oi-ai") )
( ak_0580 "# t a t oi ei t a #" ("oi-ei") )
( ak_0581 "# t a t oi oi t a #" ("oi-oi") )
( ak_0582 "# t a t oi au t a #" ("oi-au") )
( ak_0583 "# t a t oi ie t a #" ("oi-ie") )
( ak_0584 "# t a t oi ia t a #" ("oi-ia") )
( ak_0585 "# t a t oi io t a #" ("oi-io") )
( ak_0586 "# t a t oi ii t a #" ("oi-ii") )
( ak_0587 "# t a t oi iu t a #" ("oi-iu") )
( ak_0588 "# t a t oi ue t a #" ("oi-ue") )
( ak_0589 "# t a t oi ua t a #" ("oi-ua") )
( ak_0590 "# t a t oi uo t a #" ("oi-uo") )
( ak_0591 "# t a t oi ui t a #" ("oi-ui") )
( ak_0592 "# t a t oi uu t a #" ("oi-uu") )
( ak_0593 "# t a t oi iy t a #" ("oi-iy") )
( ak_0594 "# t a t oi uy t a #" ("oi-uy") )
( ak_0595 "# t a t au y t a #" ("au-y") )
( ak_0596 "# t a t au e t a #" ("au-e") )
( ak_0597 "# t a t au a t a #" ("au-a") )
( ak_0598 "# t a t au o t a #" ("au-o") )
( ak_0599 "# t a t au i t a #" ("au-i") )
( ak_0600 "# t a t au u t a #" ("au-u") )
( ak_0601 "# t a t au ai t a #" ("au-ai") )
( ak_0602 "# t a t au ei t a #" ("au-ei") )
( ak_0603 "# t a t au oi t a #" ("au-oi") )
( ak_0604 "# t a t au au t a #" ("au-au") )
( ak_0605 "# t a t au ie t a #" ("au-ie") )
( ak_0606 "# t a t au ia t a #" ("au-ia") )
( ak_0607 "# t a t au io t a #" ("au-io") )
( ak_0608 "# t a t au ii t a #" ("au-ii") )
( ak_0609 "# t a t au iu t a #" ("au-iu") )
( ak_0610 "# t a t au ue t a #" ("au-ue") )
( ak_0611 "# t a t au ua t a #" ("au-ua") )
( ak_0612 "# t a t au uo t a #" ("au-uo") )
( ak_0613 "# t a t au ui t a #" ("au-ui") )
( ak_0614 "# t a t au uu t a #" ("au-uu") )
( ak_0615 "# t a t au iy t a #" ("au-iy") )
( ak_0616 "# t a t au uy t a #" ("au-uy") )
( ak_0617 "# t a t ie y t a #" ("ie-y") )
( ak_0618 "# t a t ie e t a #" ("ie-e") )
( ak_0619 "# t a t ie a t a #" ("ie-a") )
( ak_0620 "# t a t ie o t a #" ("ie-o") )
( ak_0621 "# t a t ie i t a #" ("ie-i") )
( ak_0622 "# t a t ie u t a #" ("ie-u") )
( ak_0623 "# t a t ie ai t a #" ("ie-ai") )
( ak_0624 "# t a t ie ei t a #" ("ie-ei") )
( ak_0625 "# t a t ie oi t a #" ("ie-oi") )
( ak_0626 "# t a t ie au t a #" ("ie-au") )
( ak_0627 "# t a t ie ie t a #" ("ie-ie") )
( ak_0628 "# t a t ie ia t a #" ("ie-ia") )
( ak_0629 "# t a t ie io t a #" ("ie-io") )
( ak_0630 "# t a t ie ii t a #" ("ie-ii") )
( ak_0631 "# t a t ie iu t a #" ("ie-iu") )
( ak_0632 "# t a t ie ue t a #" ("ie-ue") )
( ak_0633 "# t a t ie ua t a #" ("ie-ua") )
( ak_0634 "# t a t ie uo t a #" ("ie-uo") )
( ak_0635 "# t a t ie ui t a #" ("ie-ui") )
( ak_0636 "# t a t ie uu t a #" ("ie-uu") )
( ak_0637 "# t a t ie iy t a #" ("ie-iy") )
( ak_0638 "# t a t ie uy t a #" ("ie-uy") )
( ak_0639 "# t a t ia y t a #" ("ia-y") )
( ak_0640 "# t a t ia e t a #" ("ia-e") )
( ak_0641 "# t a t ia a t a #" ("ia-a") )
( ak_0642 "# t a t ia o t a #" ("ia-o") )
( ak_0643 "# t a t ia i t a #" ("ia-i") )
( ak_0644 "# t a t ia u t a #" ("ia-u") )
( ak_0645 "# t a t ia ai t a #" ("ia-ai") )
( ak_0646 "# t a t ia ei t a #" ("ia-ei") )
( ak_0647 "# t a t ia oi t a #" ("ia-oi") )
( ak_0648 "# t a t ia au t a #" ("ia-au") )
( ak_0649 "# t a t ia ie t a #" ("ia-ie") )
( ak_0650 "# t a t ia ia t a #" ("ia-ia") )
( ak_0651 "# t a t ia io t a #" ("ia-io") )
( ak_0652 "# t a t ia ii t a #" ("ia-ii") )
( ak_0653 "# t a t ia iu t a #" ("ia-iu") )
( ak_0654 "# t a t ia ue t a #" ("ia-ue") )
( ak_0655 "# t a t ia ua t a #" ("ia-ua") )
( ak_0656 "# t a t ia uo t a #" ("ia-uo") )
( ak_0657 "# t a t ia ui t a #" ("ia-ui") )
( ak_0658 "# t a t ia uu t a #" ("ia-uu") )
( ak_0659 "# t a t ia iy t a #" ("ia-iy") )
( ak_0660 "# t a t ia uy t a #" ("ia-uy") )
( ak_0661 "# t a t io y t a #" ("io-y") )
( ak_0662 "# t a t io e t a #" ("io-e") )
( ak_0663 "# t a t io a t a #" ("io-a") )
( ak_0664 "# t a t io o t a #" ("io-o") )
( ak_0665 "# t a t io i t a #" ("io-i") )
( ak_0666 "# t a t io u t a #" ("io-u") )
( ak_0667 "# t a t io ai t a #" ("io-ai") )
( ak_0668 "# t a t io ei t a #" ("io-ei") )
( ak_0669 "# t a t io oi t a #" ("io-oi") )
( ak_0670 "# t a t io au t a #" ("io-au") )
( ak_0671 "# t a t io ie t a #" ("io-ie") )
( ak_0672 "# t a t io ia t a #" ("io-ia") )
( ak_0673 "# t a t io io t a #" ("io-io") )
( ak_0674 "# t a t io ii t a #" ("io-ii") )
( ak_0675 "# t a t io iu t a #" ("io-iu") )
( ak_0676 "# t a t io ue t a #" ("io-ue") )
( ak_0677 "# t a t io ua t a #" ("io-ua") )
( ak_0678 "# t a t io uo t a #" ("io-uo") )
( ak_0679 "# t a t io ui t a #" ("io-ui") )
( ak_0680 "# t a t io uu t a #" ("io-uu") )
( ak_0681 "# t a t io iy t a #" ("io-iy") )
( ak_0682 "# t a t io uy t a #" ("io-uy") )
( ak_0683 "# t a t ii y t a #" ("ii-y") )
( ak_0684 "# t a t ii e t a #" ("ii-e") )
( ak_0685 "# t a t ii a t a #" ("ii-a") )
( ak_0686 "# t a t ii o t a #" ("ii-o") )
( ak_0687 "# t a t ii i t a #" ("ii-i") )
( ak_0688 "# t a t ii u t a #" ("ii-u") )
( ak_0689 "# t a t ii ai t a #" ("ii-ai") )
( ak_0690 "# t a t ii ei t a #" ("ii-ei") )
( ak_0691 "# t a t ii oi t a #" ("ii-oi") )
( ak_0692 "# t a t ii au t a #" ("ii-au") )
( ak_0693 "# t a t ii ie t a #" ("ii-ie") )
( ak_0694 "# t a t ii ia t a #" ("ii-ia") )
( ak_0695 "# t a t ii io t a #" ("ii-io") )
( ak_0696 "# t a t ii ii t a #" ("ii-ii") )
( ak_0697 "# t a t ii iu t a #" ("ii-iu") )
( ak_0698 "# t a t ii ue t a #" ("ii-ue") )
( ak_0699 "# t a t ii ua t a #" ("ii-ua") )
( ak_0700 "# t a t ii uo t a #" ("ii-uo") )
( ak_0701 "# t a t ii ui t a #" ("ii-ui") )
( ak_0702 "# t a t ii uu t a #" ("ii-uu") )
( ak_0703 "# t a t ii iy t a #" ("ii-iy") )
( ak_0704 "# t a t ii uy t a #" ("ii-uy") )
( ak_0705 "# t a t iu y t a #" ("iu-y") )
( ak_0706 "# t a t iu e t a #" ("iu-e") )
( ak_0707 "# t a t iu a t a #" ("iu-a") )
( ak_0708 "# t a t iu o t a #" ("iu-o") )
( ak_0709 "# t a t iu i t a #" ("iu-i") )
( ak_0710 "# t a t iu u t a #" ("iu-u") )
( ak_0711 "# t a t iu ai t a #" ("iu-ai") )
( ak_0712 "# t a t iu ei t a #" ("iu-ei") )
( ak_0713 "# t a t iu oi t a #" ("iu-oi") )
( ak_0714 "# t a t iu au t a #" ("iu-au") )
( ak_0715 "# t a t iu ie t a #" ("iu-ie") )
( ak_0716 "# t a t iu ia t a #" ("iu-ia") )
( ak_0717 "# t a t iu io t a #" ("iu-io") )
( ak_0718 "# t a t iu ii t a #" ("iu-ii") )
( ak_0719 "# t a t iu iu t a #" ("iu-iu") )
( ak_0720 "# t a t iu ue t a #" ("iu-ue") )
( ak_0721 "# t a t iu ua t a #" ("iu-ua") )
( ak_0722 "# t a t iu uo t a #" ("iu-uo") )
( ak_0723 "# t a t iu ui t a #" ("iu-ui") )
( ak_0724 "# t a t iu uu t a #" ("iu-uu") )
( ak_0725 "# t a t iu iy t a #" ("iu-iy") )
( ak_0726 "# t a t iu uy t a #" ("iu-uy") )
( ak_0727 "# t a t ue y t a #" ("ue-y") )
( ak_0728 "# t a t ue e t a #" ("ue-e") )
( ak_0729 "# t a t ue a t a #" ("ue-a") )
( ak_0730 "# t a t ue o t a #" ("ue-o") )
( ak_0731 "# t a t ue i t a #" ("ue-i") )
( ak_0732 "# t a t ue u t a #" ("ue-u") )
( ak_0733 "# t a t ue ai t a #" ("ue-ai") )
( ak_0734 "# t a t ue ei t a #" ("ue-ei") )
( ak_0735 "# t a t ue oi t a #" ("ue-oi") )
( ak_0736 "# t a t ue au t a #" ("ue-au") )
( ak_0737 "# t a t ue ie t a #" ("ue-ie") )
( ak_0738 "# t a t ue ia t a #" ("ue-ia") )
( ak_0739 "# t a t ue io t a #" ("ue-io") )
( ak_0740 "# t a t ue ii t a #" ("ue-ii") )
( ak_0741 "# t a t ue iu t a #" ("ue-iu") )
( ak_0742 "# t a t ue ue t a #" ("ue-ue") )
( ak_0743 "# t a t ue ua t a #" ("ue-ua") )
( ak_0744 "# t a t ue uo t a #" ("ue-uo") )
( ak_0745 "# t a t ue ui t a #" ("ue-ui") )
( ak_0746 "# t a t ue uu t a #" ("ue-uu") )
( ak_0747 "# t a t ue iy t a #" ("ue-iy") )
( ak_0748 "# t a t ue uy t a #" ("ue-uy") )
( ak_0749 "# t a t ua y t a #" ("ua-y") )
( ak_0750 "# t a t ua e t a #" ("ua-e") )
( ak_0751 "# t a t ua a t a #" ("ua-a") )
( ak_0752 "# t a t ua o t a #" ("ua-o") )
( ak_0753 "# t a t ua i t a #" ("ua-i") )
( ak_0754 "# t a t ua u t a #" ("ua-u") )
( ak_0755 "# t a t ua ai t a #" ("ua-ai") )
( ak_0756 "# t a t ua ei t a #" ("ua-ei") )
( ak_0757 "# t a t ua oi t a #" ("ua-oi") )
( ak_0758 "# t a t ua au t a #" ("ua-au") )
( ak_0759 "# t a t ua ie t a #" ("ua-ie") )
( ak_0760 "# t a t ua ia t a #" ("ua-ia") )
( ak_0761 "# t a t ua io t a #" ("ua-io") )
( ak_0762 "# t a t ua ii t a #" ("ua-ii") )
( ak_0763 "# t a t ua iu t a #" ("ua-iu") )
( ak_0764 "# t a t ua ue t a #" ("ua-ue") )
( ak_0765 "# t a t ua ua t a #" ("ua-ua") )
( ak_0766 "# t a t ua uo t a #" ("ua-uo") )
( ak_0767 "# t a t ua ui t a #" ("ua-ui") )
( ak_0768 "# t a t ua uu t a #" ("ua-uu") )
( ak_0769 "# t a t ua iy t a #" ("ua-iy") )
( ak_0770 "# t a t ua uy t a #" ("ua-uy") )
( ak_0771 "# t a t uo y t a #" ("uo-y") )
( ak_0772 "# t a t uo e t a #" ("uo-e") )
( ak_0773 "# t a t uo a t a #" ("uo-a") )
( ak_0774 "# t a t uo o t a #" ("uo-o") )
( ak_0775 "# t a t uo i t a #" ("uo-i") )
( ak_0776 "# t a t uo u t a #" ("uo-u") )
( ak_0777 "# t a t uo ai t a #" ("uo-ai") )
( ak_0778 "# t a t uo ei t a #" ("uo-ei") )
( ak_0779 "# t a t uo oi t a #" ("uo-oi") )
( ak_0780 "# t a t uo au t a #" ("uo-au") )
( ak_0781 "# t a t uo ie t a #" ("uo-ie") )
( ak_0782 "# t a t uo ia t a #" ("uo-ia") )
( ak_0783 "# t a t uo io t a #" ("uo-io") )
( ak_0784 "# t a t uo ii t a #" ("uo-ii") )
( ak_0785 "# t a t uo iu t a #" ("uo-iu") )
( ak_0786 "# t a t uo ue t a #" ("uo-ue") )
( ak_0787 "# t a t uo ua t a #" ("uo-ua") )
( ak_0788 "# t a t uo uo t a #" ("uo-uo") )
( ak_0789 "# t a t uo ui t a #" ("uo-ui") )
( ak_0790 "# t a t uo uu t a #" ("uo-uu") )
( ak_0791 "# t a t uo iy t a #" ("uo-iy") )
( ak_0792 "# t a t uo uy t a #" ("uo-uy") )
( ak_0793 "# t a t ui y t a #" ("ui-y") )
( ak_0794 "# t a t ui e t a #" ("ui-e") )
( ak_0795 "# t a t ui a t a #" ("ui-a") )
( ak_0796 "# t a t ui o t a #" ("ui-o") )
( ak_0797 "# t a t ui i t a #" ("ui-i") )
( ak_0798 "# t a t ui u t a #" ("ui-u") )
( ak_0799 "# t a t ui ai t a #" ("ui-ai") )
( ak_0800 "# t a t ui ei t a #" ("ui-ei") )
( ak_0801 "# t a t ui oi t a #" ("ui-oi") )
( ak_0802 "# t a t ui au t a #" ("ui-au") )
( ak_0803 "# t a t ui ie t a #" ("ui-ie") )
( ak_0804 "# t a t ui ia t a #" ("ui-ia") )
( ak_0805 "# t a t ui io t a #" ("ui-io") )
( ak_0806 "# t a t ui ii t a #" ("ui-ii") )
( ak_0807 "# t a t ui iu t a #" ("ui-iu") )
( ak_0808 "# t a t ui ue t a #" ("ui-ue") )
( ak_0809 "# t a t ui ua t a #" ("ui-ua") )
( ak_0810 "# t a t ui uo t a #" ("ui-uo") )
( ak_0811 "# t a t ui ui t a #" ("ui-ui") )
( ak_0812 "# t a t ui uu t a #" ("ui-uu") )
( ak_0813 "# t a t ui iy t a #" ("ui-iy") )
( ak_0814 "# t a t ui uy t a #" ("ui-uy") )
( ak_0815 "# t a t uu y t a #" ("uu-y") )
( ak_0816 "# t a t uu e t a #" ("uu-e") )
( ak_0817 "# t a t uu a t a #" ("uu-a") )
( ak_0818 "# t a t uu o t a #" ("uu-o") )
( ak_0819 "# t a t uu i t a #" ("uu-i") )
( ak_0820 "# t a t uu u t a #" ("uu-u") )
( ak_0821 "# t a t uu ai t a #" ("uu-ai") )
( ak_0822 "# t a t uu ei t a #" ("uu-ei") )
( ak_0823 "# t a t uu oi t a #" ("uu-oi") )
( ak_0824 "# t a t uu au t a #" ("uu-au") )
( ak_0825 "# t a t uu ie t a #" ("uu-ie") )
( ak_0826 "# t a t uu ia t a #" ("uu-ia") )
( ak_0827 "# t a t uu io t a #" ("uu-io") )
( ak_0828 "# t a t uu ii t a #" ("uu-ii") )
( ak_0829 "# t a t uu iu t a #" ("uu-iu") )
( ak_0830 "# t a t uu ue t a #" ("uu-ue") )
( ak_0831 "# t a t uu ua t a #" ("uu-ua") )
( ak_0832 "# t a t uu uo t a #" ("uu-uo") )
( ak_0833 "# t a t uu ui t a #" ("uu-ui") )
( ak_0834 "# t a t uu uu t a #" ("uu-uu") )
( ak_0835 "# t a t uu iy t a #" ("uu-iy") )
( ak_0836 "# t a t uu uy t a #" ("uu-uy") )
( ak_0837 "# t a t iy y t a #" ("iy-y") )
( ak_0838 "# t a t iy e t a #" ("iy-e") )
( ak_0839 "# t a t iy a t a #" ("iy-a") )
( ak_0840 "# t a t iy o t a #" ("iy-o") )
( ak_0841 "# t a t iy i t a #" ("iy-i") )
( ak_0842 "# t a t iy u t a #" ("iy-u") )
( ak_0843 "# t a t iy ai t a #" ("iy-ai") )
( ak_0844 "# t a t iy ei t a #" ("iy-ei") )
( ak_0845 "# t a t iy oi t a #" ("iy-oi") )
( ak_0846 "# t a t iy au t a #" ("iy-au") )
( ak_0847 "# t a t iy ie t a #" ("iy-ie") )
( ak_0848 "# t a t iy ia t a #" ("iy-ia") )
( ak_0849 "# t a t iy io t a #" ("iy-io") )
( ak_0850 "# t a t iy ii t a #" ("iy-ii") )
( ak_0851 "# t a t iy iu t a #" ("iy-iu") )
( ak_0852 "# t a t iy ue t a #" ("iy-ue") )
( ak_0853 "# t a t iy ua t a #" ("iy-ua") )
( ak_0854 "# t a t iy uo t a #" ("iy-uo") )
( ak_0855 "# t a t iy ui t a #" ("iy-ui") )
( ak_0856 "# t a t iy uu t a #" ("iy-uu") )
( ak_0857 "# t a t iy iy t a #" ("iy-iy") )
( ak_0858 "# t a t iy uy t a #" ("iy-uy") )
( ak_0859 "# t a t uy y t a #" ("uy-y") )
( ak_0860 "# t a t uy e t a #" ("uy-e") )
( ak_0861 "# t a t uy a t a #" ("uy-a") )
( ak_0862 "# t a t uy o t a #" ("uy-o") )
( ak_0863 "# t a t uy i t a #" ("uy-i") )
( ak_0864 "# t a t uy u t a #" ("uy-u") )
( ak_0865 "# t a t uy ai t a #" ("uy-ai") )
( ak_0866 "# t a t uy ei t a #" ("uy-ei") )
( ak_0867 "# t a t uy oi t a #" ("uy-oi") )
( ak_0868 "# t a t uy au t a #" ("uy-au") )
( ak_0869 "# t a t uy ie t a #" ("uy-ie") )
( ak_0870 "# t a t uy ia t a #" ("uy-ia") )
( ak_0871 "# t a t uy io t a #" ("uy-io") )
( ak_0872 "# t a t uy ii t a #" ("uy-ii") )
( ak_0873 "# t a t uy iu t a #" ("uy-iu") )
( ak_0874 "# t a t uy ue t a #" ("uy-ue") )
( ak_0875 "# t a t uy ua t a #" ("uy-ua") )
( ak_0876 "# t a t uy uo t a #" ("uy-uo") )
( ak_0877 "# t a t uy ui t a #" ("uy-ui") )
( ak_0878 "# t a t uy uu t a #" ("uy-uu") )
( ak_0879 "# t a t uy iy t a #" ("uy-iy") )
( ak_0880 "# t a t uy uy t a #" ("uy-uy") )
( ak_0881 "# t a p - t a t a #" ("p-t") )
( ak_0882 "# t a p - k a t a #" ("p-k") )
( ak_0883 "# t a p - f a t a #" ("p-f") )
( ak_0884 "# t a p - s a t a #" ("p-s") )
( ak_0885 "# t a p - c a t a #" ("p-c") )
( ak_0886 "# t a p - x a t a #" ("p-x") )
( ak_0887 "# t a p - m a t a #" ("p-m") )
( ak_0888 "# t a p - n a t a #" ("p-n") )
( ak_0889 "# t a p - l a t a #" ("p-l") )
( ak_0890 "# t a p - r a t a #" ("p-r") )
( ak_0891 "# t a t - p a t a #" ("t-p") )
( ak_0892 "# t a t - k a t a #" ("t-k") )
( ak_0893 "# t a t - f a t a #" ("t-f") )
( ak_0894 "# t a t - s a t a #" ("t-s") )
( ak_0895 "# t a t - c a t a #" ("t-c") )
( ak_0896 "# t a t - x a t a #" ("t-x") )
( ak_0897 "# t a t - m a t a #" ("t-m") )
( ak_0898 "# t a t - n a t a #" ("t-n") )
( ak_0899 "# t a t - l a t a #" ("t-l") )
( ak_0900 "# t a t - r a t a #" ("t-r") )
( ak_0901 "# t a k - p a t a #" ("k-p") )
( ak_0902 "# t a k - t a t a #" ("k-t") )
( ak_0903 "# t a k - f a t a #" ("k-f") )
( ak_0904 "# t a k - s a t a #" ("k-s") )
( ak_0905 "# t a k - c a t a #" ("k-c") )
( ak_0906 "# t a k - m a t a #" ("k-m") )
( ak_0907 "# t a k - n a t a #" ("k-n") )
( ak_0908 "# t a k - l a t a #" ("k-l") )
( ak_0909 "# t a k - r a t a #" ("k-r") )
( ak_0910 "# t a f - p a t a #" ("f-p") )
( ak_0911 "# t a f - t a t a #" ("f-t") )
( ak_0912 "# t a f - k a t a #" ("f-k") )
( ak_0913 "# t a f - s a t a #" ("f-s") )
( ak_0914 "# t a f - c a t a #" ("f-c") )
( ak_0915 "# t a f - x a t a #" ("f-x") )
( ak_0916 "# t a f - m a t a #" ("f-m") )
( ak_0917 "# t a f - n a t a #" ("f-n") )
( ak_0918 "# t a f - l a t a #" ("f-l") )
( ak_0919 "# t a f - r a t a #" ("f-r") )
( ak_0920 "# t a b - d a t a #" ("b-d") )
( ak_0921 "# t a b - g a t a #" ("b-g") )
( ak_0922 "# t a b - v a t a #" ("b-v") )
( ak_0923 "# t a b - z a t a #" ("b-z") )
( ak_0924 "# t a b - j a t a #" ("b-j") )
( ak_0925 "# t a b - m a t a #" ("b-m") )
( ak_0926 "# t a b - n a t a #" ("b-n") )
( ak_0927 "# t a b - l a t a #" ("b-l") )
( ak_0928 "# t a b - r a t a #" ("b-r") )
( ak_0929 "# t a d - b a t a #" ("d-b") )
( ak_0930 "# t a d - g a t a #" ("d-g") )
( ak_0931 "# t a d - v a t a #" ("d-v") )
( ak_0932 "# t a d - z a t a #" ("d-z") )
( ak_0933 "# t a d - j a t a #" ("d-j") )
( ak_0934 "# t a d - m a t a #" ("d-m") )
( ak_0935 "# t a d - n a t a #" ("d-n") )
( ak_0936 "# t a d - l a t a #" ("d-l") )
( ak_0937 "# t a d - r a t a #" ("d-r") )
( ak_0938 "# t a g - b a t a #" ("g-b") )
( ak_0939 "# t a g - d a t a #" ("g-d") )
( ak_0940 "# t a g - v a t a #" ("g-v") )
( ak_0941 "# t a g - z a t a #" ("g-z") )
( ak_0942 "# t a g - j a t a #" ("g-j") )
( ak_0943 "# t a g - m a t a #" ("g-m") )
( ak_0944 "# t a g - n a t a #" ("g-n") )
( ak_0945 "# t a g - l a t a #" ("g-l") )
( ak_0946 "# t a g - r a t a #" ("g-r") )
( ak_0947 "# t a v - b a t a #" ("v-b") )
( ak_0948 "# t a v - d a t a #" ("v-d") )
( ak_0949 "# t a v - g a t a #" ("v-g") )
( ak_0950 "# t a v - z a t a #" ("v-z") )
( ak_0951 "# t a v - j a t a #" ("v-j") )
( ak_0952 "# t a v - m a t a #" ("v-m") )
( ak_0953 "# t a v - n a t a #" ("v-n") )
( ak_0954 "# t a v - l a t a #" ("v-l") )
( ak_0955 "# t a v - r a t a #" ("v-r") )
( ak_0956 "# t a s - p a t a #" ("s-p") )
( ak_0957 "# t a s - t a t a #" ("s-t") )
( ak_0958 "# t a s - k a t a #" ("s-k") )
( ak_0959 "# t a s - f a t a #" ("s-f") )
( ak_0960 "# t a s - x a t a #" ("s-x") )
( ak_0961 "# t a s - m a t a #" ("s-m") )
( ak_0962 "# t a s - n a t a #" ("s-n") )
( ak_0963 "# t a s - l a t a #" ("s-l") )
( ak_0964 "# t a s - r a t a #" ("s-r") )
( ak_0965 "# t a z - b a t a #" ("z-b") )
( ak_0966 "# t a z - d a t a #" ("z-d") )
( ak_0967 "# t a z - g a t a #" ("z-g") )
( ak_0968 "# t a z - v a t a #" ("z-v") )
( ak_0969 "# t a z - m a t a #" ("z-m") )
( ak_0970 "# t a z - n a t a #" ("z-n") )
( ak_0971 "# t a z - l a t a #" ("z-l") )
( ak_0972 "# t a z - r a t a #" ("z-r") )
( ak_0973 "# t a c - p a t a #" ("c-p") )
( ak_0974 "# t a c - t a t a #" ("c-t") )
( ak_0975 "# t a c - k a t a #" ("c-k") )
( ak_0976 "# t a c - f a t a #" ("c-f") )
( ak_0977 "# t a c - m a t a #" ("c-m") )
( ak_0978 "# t a c - n a t a #" ("c-n") )
( ak_0979 "# t a c - l a t a #" ("c-l") )
( ak_0980 "# t a c - r a t a #" ("c-r") )
( ak_0981 "# t a j - b a t a #" ("j-b") )
( ak_0982 "# t a j - d a t a #" ("j-d") )
( ak_0983 "# t a j - g a t a #" ("j-g") )
( ak_0984 "# t a j - v a t a #" ("j-v") )
( ak_0985 "# t a j - m a t a #" ("j-m") )
( ak_0986 "# t a j - n a t a #" ("j-n") )
( ak_0987 "# t a j - l a t a #" ("j-l") )
( ak_0988 "# t a j - r a t a #" ("j-r") )
( ak_0989 "# t a x - p a t a #" ("x-p") )
( ak_0990 "# t a x - t a t a #" ("x-t") )
( ak_0991 "# t a x - f a t a #" ("x-f") )
( ak_0992 "# t a x - s a t a #" ("x-s") )
( ak_0993 "# t a x - m a t a #" ("x-m") )
( ak_0994 "# t a x - n a t a #" ("x-n") )
( ak_0995 "# t a x - l a t a #" ("x-l") )
( ak_0996 "# t a x - r a t a #" ("x-r") )
( ak_0997 "# t a m - p a t a #" ("m-p") )
( ak_0998 "# t a m - t a t a #" ("m-t") )
( ak_0999 "# t a m - k a t a #" ("m-k") )
( ak_1000 "# t a m - f a t a #" ("m-f") )
( ak_1001 "# t a m - b a t a #" ("m-b") )
( ak_1002 "# t a m - d a t a #" ("m-d") )
( ak_1003 "# t a m - g a t a #" ("m-g") )
( ak_1004 "# t a m - v a t a #" ("m-v") )
( ak_1005 "# t a m - s a t a #" ("m-s") )
( ak_1006 "# t a m - c a t a #" ("m-c") )
( ak_1007 "# t a m - j a t a #" ("m-j") )
( ak_1008 "# t a m - x a t a #" ("m-x") )
( ak_1009 "# t a m - n a t a #" ("m-n") )
( ak_1010 "# t a m - l a t a #" ("m-l") )
( ak_1011 "# t a m - r a t a #" ("m-r") )
( ak_1012 "# t a n - p a t a #" ("n-p") )
( ak_1013 "# t a n - t a t a #" ("n-t") )
( ak_1014 "# t a n - k a t a #" ("n-k") )
( ak_1015 "# t a n - f a t a #" ("n-f") )
( ak_1016 "# t a n - b a t a #" ("n-b") )
( ak_1017 "# t a n - d a t a #" ("n-d") )
( ak_1018 "# t a n - g a t a #" ("n-g") )
( ak_1019 "# t a n - v a t a #" ("n-v") )
( ak_1020 "# t a n - s a t a #" ("n-s") )
( ak_1021 "# t a n - z a t a #" ("n-z") )
( ak_1022 "# t a n - c a t a #" ("n-c") )
( ak_1023 "# t a n - j a t a #" ("n-j") )
( ak_1024 "# t a n - x a t a #" ("n-x") )
( ak_1025 "# t a n - m a t a #" ("n-m") )
( ak_1026 "# t a n - l a t a #" ("n-l") )
( ak_1027 "# t a n - r a t a #" ("n-r") )
( ak_1028 "# t a l - p a t a #" ("l-p") )
( ak_1029 "# t a l - t a t a #" ("l-t") )
( ak_1030 "# t a l - k a t a #" ("l-k") )
( ak_1031 "# t a l - f a t a #" ("l-f") )
( ak_1032 "# t a l - b a t a #" ("l-b") )
( ak_1033 "# t a l - d a t a #" ("l-d") )
( ak_1034 "# t a l - g a t a #" ("l-g") )
( ak_1035 "# t a l - v a t a #" ("l-v") )
( ak_1036 "# t a l - s a t a #" ("l-s") )
( ak_1037 "# t a l - z a t a #" ("l-z") )
( ak_1038 "# t a l - c a t a #" ("l-c") )
( ak_1039 "# t a l - j a t a #" ("l-j") )
( ak_1040 "# t a l - x a t a #" ("l-x") )
( ak_1041 "# t a l - m a t a #" ("l-m") )
( ak_1042 "# t a l - n a t a #" ("l-n") )
( ak_1043 "# t a l - r a t a #" ("l-r") )
( ak_1044 "# t a r - p a t a #" ("r-p") )
( ak_1045 "# t a r - t a t a #" ("r-t") )
( ak_1046 "# t a r - k a t a #" ("r-k") )
( ak_1047 "# t a r - f a t a #" ("r-f") )
( ak_1048 "# t a r - b a t a #" ("r-b") )
( ak_1049 "# t a r - d a t a #" ("r-d") )
( ak_1050 "# t a r - g a t a #" ("r-g") )
( ak_1051 "# t a r - v a t a #" ("r-v") )
( ak_1052 "# t a r - s a t a #" ("r-s") )
( ak_1053 "# t a r - z a t a #" ("r-z") )
( ak_1054 "# t a r - c a t a #" ("r-c") )
( ak_1055 "# t a r - j a t a #" ("r-j") )
( ak_1056 "# t a r - x a t a #" ("r-x") )
( ak_1057 "# t a r - m a t a #" ("r-m") )
( ak_1058 "# t a r - n a t a #" ("r-n") )
( ak_1059 "# t a r - l a t a #" ("r-l") )
( ak_1060 "# t a - b l a t a #" ("b_-_l") )
( ak_1061 "# t a - b r a t a #" ("b_-_r") )
( ak_1062 "# t a - c f a t a #" ("c_-_f") )
( ak_1063 "# t a - c k a t a #" ("c_-_k") )
( ak_1064 "# t a - c l a t a #" ("c_-_l") )
( ak_1065 "# t a - c m a t a #" ("c_-_m") )
( ak_1066 "# t a - c n a t a #" ("c_-_n") )
( ak_1067 "# t a - c p a t a #" ("c_-_p") )
( ak_1068 "# t a - c r a t a #" ("c_-_r") )
( ak_1069 "# t a - c t a t a #" ("c_-_t") )
( ak_1070 "# t a - d j a t a #" ("d_-_j") )
( ak_1071 "# t a - d r a t a #" ("d_-_r") )
( ak_1072 "# t a - d z a t a #" ("d_-_z") )
( ak_1073 "# t a - f l a t a #" ("f_-_l") )
( ak_1074 "# t a - f r a t a #" ("f_-_r") )
( ak_1075 "# t a - g l a t a #" ("g_-_l") )
( ak_1076 "# t a - g r a t a #" ("g_-_r") )
( ak_1077 "# t a - j b a t a #" ("j_-_b") )
( ak_1078 "# t a - j d a t a #" ("j_-_d") )
( ak_1079 "# t a - j g a t a #" ("j_-_g") )
( ak_1080 "# t a - j m a t a #" ("j_-_m") )
( ak_1081 "# t a - j v a t a #" ("j_-_v") )
( ak_1082 "# t a - k l a t a #" ("k_-_l") )
( ak_1083 "# t a - k r a t a #" ("k_-_r") )
( ak_1084 "# t a - m l a t a #" ("m_-_l") )
( ak_1085 "# t a - m r a t a #" ("m_-_r") )
( ak_1086 "# t a - p l a t a #" ("p_-_l") )
( ak_1087 "# t a - p r a t a #" ("p_-_r") )
( ak_1088 "# t a - s f a t a #" ("s_-_f") )
( ak_1089 "# t a - s k a t a #" ("s_-_k") )
( ak_1090 "# t a - s l a t a #" ("s_-_l") )
( ak_1091 "# t a - s m a t a #" ("s_-_m") )
( ak_1092 "# t a - s n a t a #" ("s_-_n") )
( ak_1093 "# t a - s p a t a #" ("s_-_p") )
( ak_1094 "# t a - s r a t a #" ("s_-_r") )
( ak_1095 "# t a - s t a t a #" ("s_-_t") )
( ak_1096 "# t a - t c a t a #" ("t_-_c") )
( ak_1097 "# t a - t r a t a #" ("t_-_r") )
( ak_1098 "# t a - t s a t a #" ("t_-_s") )
( ak_1099 "# t a - v l a t a #" ("v_-_l") )
( ak_1100 "# t a - v r a t a #" ("v_-_r") )
( ak_1101 "# t a - x l a t a #" ("x_-_l") )
( ak_1102 "# t a - x r a t a #" ("x_-_r") )
( ak_1103 "# t a - z b a t a #" ("z_-_b") )
( ak_1104 "# t a - z d a t a #" ("z_-_d") )
( ak_1105 "# t a - z g a t a #" ("z_-_g") )
( ak_1106 "# t a - z m a t a #" ("z_-_m") )
( ak_1107 "# t a - z v a t a #" ("z_-_v") )
( ak_1108 "# y t a #" ("#-y") )
( ak_1109 "# e t a #" ("#-e") )
( ak_1110 "# a t a #" ("#-a") )
( ak_1111 "# o t a #" ("#-o") )
( ak_1112 "# i t a #" ("#-i") )
( ak_1113 "# u t a #" ("#-u") )
( ak_1114 "# ai t a #" ("#-ai") )
( ak_1115 "# ei t a #" ("#-ei") )
( ak_1116 "# oi t a #" ("#-oi") )
( ak_1117 "# au t a #" ("#-au") )
( ak_1118 "# ie t a #" ("#-ie") )
( ak_1119 "# ia t a #" ("#-ia") )
( ak_1120 "# io t a #" ("#-io") )
( ak_1121 "# ii t a #" ("#-ii") )
( ak_1122 "# iu t a #" ("#-iu") )
( ak_1123 "# ue t a #" ("#-ue") )
( ak_1124 "# ua t a #" ("#-ua") )
( ak_1125 "# uo t a #" ("#-uo") )
( ak_1126 "# ui t a #" ("#-ui") )
( ak_1127 "# uu t a #" ("#-uu") )
( ak_1128 "# iy t a #" ("#-iy") )
( ak_1129 "# uy t a #" ("#-uy") )
( ak_1130 "# p a t a #" ("#-p") )
( ak_1131 "# t a t a #" ("#-t") )
( ak_1132 "# k a t a #" ("#-k") )
( ak_1133 "# f a t a #" ("#-f") )
( ak_1134 "# b a t a #" ("#-b") )
( ak_1135 "# d a t a #" ("#-d") )
( ak_1136 "# g a t a #" ("#-g") )
( ak_1137 "# v a t a #" ("#-v") )
( ak_1138 "# s a t a #" ("#-s") )
( ak_1139 "# z a t a #" ("#-z") )
( ak_1140 "# c a t a #" ("#-c") )
( ak_1141 "# j a t a #" ("#-j") )
( ak_1142 "# x a t a #" ("#-x") )
( ak_1143 "# m a t a #" ("#-m") )
( ak_1144 "# n a t a #" ("#-n") )
( ak_1145 "# l a t a #" ("#-l") )
( ak_1146 "# r a t a #" ("#-r") )
( ak_1147 "# t a t a p #" ("p-#") )
( ak_1148 "# t a t a t #" ("t-#") )
( ak_1149 "# t a t a k #" ("k-#") )
( ak_1150 "# t a t a f #" ("f-#") )
( ak_1151 "# t a t a b #" ("b-#") )
( ak_1152 "# t a t a d #" ("d-#") )
( ak_1153 "# t a t a g #" ("g-#") )
( ak_1154 "# t a t a v #" ("v-#") )
( ak_1155 "# t a t a s #" ("s-#") )
( ak_1156 "# t a t a z #" ("z-#") )
( ak_1157 "# t a t a c #" ("c-#") )
( ak_1158 "# t a t a j #" ("j-#") )
( ak_1159 "# t a t a x #" ("x-#") )
( ak_1160 "# t a t a m #" ("m-#") )
( ak_1161 "# t a t a n #" ("n-#") )
( ak_1162 "# t a t a l #" ("l-#") )
( ak_1163 "# t a t a r #" ("r-#") )
( ak_1164 "# t a t y #" ("y-#") )
( ak_1165 "# t a t e #" ("e-#") )
( ak_1166 "# t a t a #" ("a-#") )
( ak_1167 "# t a t o #" ("o-#") )
( ak_1168 "# t a t i #" ("i-#") )
( ak_1169 "# t a t u #" ("u-#") )
( ak_1170 "# t a t ai #" ("ai-#") )
( ak_1171 "# t a t ei #" ("ei-#") )
( ak_1172 "# t a t oi #" ("oi-#") )
( ak_1173 "# t a t au #" ("au-#") )
( ak_1174 "# t a t ie #" ("ie-#") )
( ak_1175 "# t a t ia #" ("ia-#") )
( ak_1176 "# t a t io #" ("io-#") )
( ak_1177 "# t a t ii #" ("ii-#") )
( ak_1178 "# t a t iu #" ("iu-#") )
( ak_1179 "# t a t ue #" ("ue-#") )
( ak_1180 "# t a t ua #" ("ua-#") )
( ak_1181 "# t a t uo #" ("uo-#") )
( ak_1182 "# t a t ui #" ("ui-#") )
( ak_1183 "# t a t uu #" ("uu-#") )
( ak_1184 "# t a t iy #" ("iy-#") )
( ak_1185 "# t a t uy #" ("uy-#") )
( ak_1186 "# t a t a # #" ("#-#") )
