((jbo "purmo")
 (en "powder")
 )
((jbo "lalxu")
 (en unknown)
 )
((jbo "botpi")
 (en "bottle/jar/flask/closable container @ for @ of material @ with lid @")
 )
((jbo "crino")
 (en "@ is green")
 )
((jbo "farlu")
 (en "fall")
 )
((jbo "minji")
 (en "green/machine")
 (note "unclear meaning")
 )
((jbo "temci")
 (en "time")
 )
((jbo "selma'o")
 (from "se cmavo")
 (en "cmavo class")
 )
((jbo "sonci")
 (en "@ is a soldier/fighter of army @"))
((jbo "guntrusi'o")
 (en "Communist")
 (enplex "work-govern-idea")
 )
